import { IBienBanHop } from "../model/BienBanHopModel";

export const initBienBanHop: IBienBanHop = {
    id: '',
    departmentId: '',
    code: '',
    bienBan: '',
    name: '',
    suCoId: '',
    ngayGioHop: '',
    ngayHop: '',
    gioHop: '',
    diaDiem: '',
    noiDung: '',
    chuTriId: '',
    tenChuTri: '',
    tenChucDanhChuTri: '',
    tenChucVuChuTri: '',
    thuKyId: '',
    thuKyObj: null,
    chuTriObj: null,
    trinhBayObj: null,
    tenThuKy: '',
    tenChucDanhThuKy: '',
    tenChucVuThuKy: '',
    nguoiTrinhBayId: '',
    tenNguoiTrinhBay: '',
    tenChucDanhNguoiTrinhBay: '',
    tenChucVuNguoiTrinhBay: '',
    soThanhVienCoMat: null,
    tongSo: null,
    tomTatNoiDung: '',
    thaoLuan: '',
    yKien: '',
    bieuQuyet: '',
    ngayGioKetThuc: '',
    ngayKetThuc: '',
    gioKetThuc: '',
    noiNhan: [],
    isChuTriKy: null,
    isThuKyKy: null,
    trangThaiXuLy: 0,
    ketLuan: '',
    isActive: true

};