export const ConstantList = {
  ENTER_KEY: "Enter",
};
export enum SELECT_OPTION {
  SELECT_ACTION = "select-option",
  CLEAR_ACTION = "clear",
  REMOVE_ACTION = "remove-value",
}

export const PERMISSIONS = {
  AUTHORITY: "AUTHORITY",
  ROLE: "ROLE",
  USER: "USER",
  TONG_QUAN:"TONG_QUAN",
  CHAM_CONG: "CHAM_CONG",
  ORGANIZATION: "ORGANIZATION",
  THUYEN_CHUYEN: "THUYEN_CHUYEN",
  EMPLOYEE: "EMPLOYEE",
  HOP_DONG: "HOP_DONG",
  NGHI_VIEC: "NGHI_VIEC",
  KHEN_THUONG: "KHEN_THUONG",
  BO_NHIEM: "BO_NHIEM",
  MIEN_NHIEM: "MIEN_NHIEM",
  PHUC_LOI: "PHUC_LOI",
  SU_CO: "SU_CO",
  DE_XUAT: "DE_XUAT",
  BAO_HIEM_Y_TE: "BAO_HIEM_Y_TE",
  MANAGEMENT_UNIT: "MANAGEMENT_UNIT",
  TAM_UNG: "TAM_UNG",
  THANH_TOAN: "THANH_TOAN",
  DANH_MUC: "DANH_MUC", 
  //pending authorities
  DONG_PHUC: "DONG_PHUC",
  QUY_HOACH: "QUY_HOACH",
  BAO_CAO: "BAO_CAO",
  TUYEN_DUNG: "TUYEN_DUNG",
  DAO_TAO: "DAO_TAO",
  PHONG_HOP: "PHONG_HOP", 
  CONG_VIEC: "CONG_VIEC",
  TAI_LIEU: "TAI_LIEU",
  PROJECT: "PROJECT",
  REPORT : "REPORT",
  MODULE: "MODULE",
  LUONG: "LUONG"
}

export const PERMISSION_ABILITY = {
  VIEW: "VIEW",
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  UPLOAD: "UPLOAD",
  EXPORT: "EXPORT"
}

export const MODULE = {
  HO_SO: "HO_SO",
  TUYEN_DUNG: "TUYEN_DUNG",
  CHAM_CONG: "CHAM_CONG",
  TAI_LIEU: "TAI_LIEU",
  DAO_TAO: "DAO_TAO",
  PHONG_HOP: "PHONG_HOP",
  CONG_VIEC: "CONG_VIEC",
  HE_THONG: "HE_THONG"
}

export const ROLE = {
  USER: "ROLE_USER",
}